### PR TITLE
Filter Games and Achievements

### LINKED ISSUE #88: [Request] Add search bar for achievments
Could you please add search bar for achievments to quickly find achievs i want to unlock?

### LINKED ISSUE #132: Hide unlocked achievements
Could you add a button that hides unlucked achievements ? or at least an option to sort it by unlock status, I'ts pretty hard to search for achievements in games that have hundreds of them :)

### PR DESCRIPTION
**Pull request by lieberung**
Fixes #88
Fixes #132

Game list : Add Filter textbox
Achievement list : Add Filter textbox (name and description)
Achievement list : Add "Show Locked/Unlocked Only" buttons

### CODE REVIEW

**Comment by PlanK69** [comment]
Question: How do i add this change, to the regular release of SAM? (this one https://github.com/gibbed/SteamAchievementManager/releases/tag/7.0.25 ). I find the 'not being able to search my games' thing really irritating as well and a big time waster). im new to github, thanks.

**Comment by AndersonPGS** [comment]
Please accept this updated, is very amazing

**Review by AstroOrbis — APPROVED** [review]

**Comment by MartinSorani** [comment]
@gibbed are you still maintaining the project? if not, may I create a release with this change?

**Comment by darkmain** [comment]
@MartinSorani If you are alive, please please do that.

**Comment by LyraKush** [comment]
@gibbed I don't know if it's possible, seeing that SAM hasn't been updated in over 5 years, but there's some way to release achievements in the same sequence as playing.

SAM would check the "Global Achievements" and see which ones are unlocked first, I think all achievements unlocked at the same time and on the same day are ugly, it is clear that it is something editable. But of course I don't know if it's possible and viable.

Sorry for the English, I'm using the translator.

**Comment by MRxing11** [comment]
怎么联系你

**Review by xPaw — CHANGES_REQUESTED** [review]
Tried this, it should clear the logo download queue when filtering because if you filter down to 1 game, it's still dowloading thousands of images. (there's code for this in OnAddGame).

Adding a game by id should clear the filter.

**Pull request merged**
